### ISSUE TITLE
Could not pass event PlayerInteractEvent to NOPE v1.6.3

### ISSUE THREAD

**Issue by DumplingSaint** [MSWS/NOPE#136]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
1.15.2 Paper-332
**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
1.6.2
**What is the bug?**
_Please be descriptive_
Crash
**Please list your plugins below**
https://gyazo.com/ed4d1c181dab48cc98b2c97f1949c568
**Is there anything else to add?**
_Are there any error logs?_
>.... [19:14:47 ERROR]: Could not pass event PlayerInteractEvent to NOPE v1.6.3
java.lang.IllegalStateException: Start block missed in BlockIterator
at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:171) ~[patched_1.15.2.jar:git-Paper-354]
at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:236) ~[patched_1.15.2.jar:git-Paper-354]
at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:277) ~[patched_1.15.2.jar:git-Paper-354]
at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.getLineOfSight(CraftLivingEntity.java:173) ~[patched_1.15.2.jar:git-Paper-354]
at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.getTargetBlock(CraftLivingEntity.java:195) ~[patched_1.15.2.jar:git-Paper-354]
at xyz.msws.nope.checks.world.Scaffold3.onBlockPlace(Scaffold3.java:47) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor685.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-354]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-354]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-354]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-354]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:471) ~[patched_1.15.2.jar:git-Paper-354]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:438) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:143) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1360) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1059) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974) ~[patched_1.15.2.jar:git-Paper-354]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by DumplingSaint** [comment]
A guy with a hacked client is joining and it crashes as soon as he joins

**Comment by DumplingSaint** [comment]
He is using the newest version of Wurst.

**Comment by MSWS** [comment]
Does this happen on a vanilla client? What hacks does the person have enabled? Have they tried disabling them and then trying to join?

**Comment by DumplingSaint** [comment]
He disabled the client and is able to join. Doesn't happen on a vanilla client. He is not sure what hack specifically caused it but he believes it is packet related.

**Comment by MSWS** [comment]
Can you try to find out which hack is causing the issue? I’m guessing it’s nuker. Try joining a survival world and disabling all hacks except one and join until it happens.

**Comment by DumplingSaint** [comment]
He said it was an item generator and nuker.

**Comment by MSWS** [comment]
Interesting, I’ll investigate it later however this is more of a _feature_ than a bug.
