### ISSUE TITLE
Crash - Cannot load plugins/NOPE/data/89632dda91774565bf5ff02f639b1623.yml

### ISSUE THREAD

**Issue by DumplingSaint** [MSWS/NOPE#152]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
Paper 332 Mc 1.15.2
**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
1.6.3
**What is the bug?**
_Please be descriptive_
Crash, even after deleting the data folder as you recommended.
**Please list your plugins below**
https://gyazo.com/eeff15a6babdf3f00bf43c75ee11c2ad
**Is there anything else to add?**
_Are there any error logs?_
>.... [19:08:33 ERROR]: Cannot load plugins/NOPE/data/89632dda91774565bf5ff02f639b1623.yml
java.io.IOException: Cannot allocate memory
at java.io.FileInputStream.readBytes(Native Method) ~[?:1.8.0_242]
at java.io.FileInputStream.read(FileInputStream.java:255) ~[?:1.8.0_242]
at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[?:1.8.0_242]
at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:1.8.0_242]
at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:1.8.0_242]
at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.8.0_242]
at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:1.8.0_242]
at java.io.BufferedReader.readLine(BufferedReader.java:324) ~[?:1.8.0_242]
at java.io.BufferedReader.readLine(BufferedReader.java:389) ~[?:1.8.0_242]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:152) ~[patched_1.15.2.jar:git-Paper-371]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.15.2.jar:git-Paper-371]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:183) ~[patched_1.15.2.jar:git-Paper-371]
at xyz.msws.nope.modules.data.CPlayer.<init>(CPlayer.java:74) ~[?:?]
at xyz.msws.nope.modules.data.PlayerManager.getPlayer(PlayerManager.java:45) ~[?:?]
at xyz.msws.nope.NOPE.getCPlayer(NOPE.java:433) ~[?:?]
at xyz.msws.nope.checks.combat.AutoClicker1.onInteract(AutoClicker1.java:57) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor699.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-371]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-371]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-371]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-371]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:471) ~[patched_1.15.2.jar:git-Paper-371]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:438) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:143) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1365) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1059) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974) ~[patched_1.15.2.jar:git-Paper-371]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by MSWS** [comment]
> java.io.IOException: Cannot allocate memory

You are out of memory.

**Comment by DumplingSaint** [comment]
No other plugin causes it to crash like this though?
