### ISSUE TITLE
net.minecraft.server.null.EntityPose - Class not found on Paper198 1.16.3

### ISSUE THREAD

**Issue by ProductiveAsparagus56** [MSWS/NOPE#205]
**What server version are you running?**
1.16.3 Paper-198

**What version of NOPE are you running?**
1.8.2

**If Posting, please put any config files in a paste service and provide a link (pastebin, paste.md-5.net etc.)**
Using stock config files for nope and protocollib since im testing.

**What is the bug?**
Error when player joins, everything continues as followed but no checks.

**Please list your plugins below**
NOPE 1.8.2
Protocollib v4.6.0-SNAPSHOT-b480

**Is there anything else to add?**
Error log:
```java
[13:58:48 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.null.EntityPose
[13:58:48 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105)
[13:58:48 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[13:58:48 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[13:58:48 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[13:58:48 WARN]:        at java.lang.Class.forName0(Native Method)
[13:58:48 WARN]:        at java.lang.Class.forName(Class.java:264)
[13:58:48 WARN]:        at xyz.msws.nope.modules.npc.NPC.spawn(NPC.java:157)
[13:58:48 WARN]:        at xyz.msws.nope.checks.packet.PlayerESP1.spawnNPCs(PlayerESP1.java:145)
[13:58:48 WARN]:        at xyz.msws.nope.checks.packet.PlayerESP1.onJoin(PlayerESP1.java:104)
[13:58:48 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor16.execute(Unknown Source)
[13:58:48 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[13:58:48 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:58:48 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:58:48 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[13:58:48 WARN]:        at net.minecraft.server.v1_16_R2.PlayerList.postChunkLoadJoin(PlayerList.java:273)
[13:58:48 WARN]:        at net.minecraft.server.v1_16_R2.PlayerList.lambda$null$1(PlayerList.java:220)
[13:58:48 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnection.tick(PlayerConnection.java:154)
[13:58:48 WARN]:        at net.minecraft.server.v1_16_R2.NetworkManager.a(NetworkManager.java:385)
[13:58:48 WARN]:        at net.minecraft.server.v1_16_R2.ServerConnection.c(ServerConnection.java:145)
[13:58:48 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1383)
[13:58:48 WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
[13:58:48 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
[13:58:48 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[13:58:48 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[13:58:48 WARN]:        at java.lang.Thread.run(Thread.java:748)
[13:58:48 ERROR]: Could not pass event PlayerJoinEvent to NOPE v1.8.2
java.lang.NullPointerException: null
        at xyz.msws.nope.modules.npc.NPC.spawn(NPC.java:182) ~[?:?]
        at xyz.msws.nope.checks.packet.PlayerESP1.spawnNPCs(PlayerESP1.java:145) ~[?:?]
        at xyz.msws.nope.checks.packet.PlayerESP1.onJoin(PlayerESP1.java:104) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor16.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-198]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-198]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-198]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-198]
        at net.minecraft.server.v1_16_R2.PlayerList.postChunkLoadJoin(PlayerList.java:273) ~[patched_1.16.3.jar:git-Paper-198]
        at net.minecraft.server.v1_16_R2.PlayerList.lambda$null$1(PlayerList.java:220) ~[patched_1.16.3.jar:git-Paper-198]
        at net.minecraft.server.v1_16_R2.PlayerConnection.tick(PlayerConnection.java:154) ~[patched_1.16.3.jar:git-Paper-198]
        at net.minecraft.server.v1_16_R2.NetworkManager.a(NetworkManager.java:385) ~[patched_1.16.3.jar:git-Paper-198]
        at net.minecraft.server.v1_16_R2.ServerConnection.c(ServerConnection.java:145) ~[patched_1.16.3.jar:git-Paper-198]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1383) ~[patched_1.16.3.jar:git-Paper-198]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-198]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-198]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-198]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-198]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

**Comment by ProductiveAsparagus56** [comment]
@MSWS I understand your frustration with all the bug reports from people that don't really understand a lot about plugins anyway, I hope i did it a little better so its easier for you to work with :)

**Comment by ProductiveAsparagus56** [comment]
Problem has to mostly do with protocollib, we all have to wait until they release full support for 1.16.x

Closing this issue.
